Repository GeekTree0101/VEditorKit, pull requests merged in 2019-01, with the labels that each got.

#3 VEditorKit Typing Control Spec
  Example/VEditorKit.xcodeproj/project.pbxproj
  Example/VEditorKit/EditorControlAreaNode.swift
  Example/VEditorKit/EditorNodeController.swift
  Example/VEditorKit/EditorRule.swift
  Example/VEditorKit/Images.xcassets/Contents.json
  Example/VEditorKit/Images.xcassets/keyboard.imageset/Contents.json
  Example/VEditorKit/Images.xcassets/keyboard.imageset/keyboard.png
  Example/VEditorKit/Images.xcassets/keyboard.png
  VEditorKit/Classes/VEditorNode.swift
  VEditorKit/Classes/VEditorTextCellNode.swift
  VEditorKit/Classes/VEditorTextNode.swift
  VEditorKit/Classes/VEditorTextStorage.swift
  VEditorKit/Classes/VEditorTypingControlNode.swift
Labels: enhancement

#4 VEditorKit should be able to manage typing controls
  .swift-version
  .travis.yml
  Example/VEditorKit/EditorControlAreaNode.swift
  Example/VEditorKit/EditorNodeController.swift
  Example/VEditorKit/EditorRule.swift
  VEditorKit.podspec
  VEditorKit/Classes/Platform.swift
  VEditorKit/Classes/VEditorNode.swift
  VEditorKit/Classes/VEditorOpenGraphNode.swift
  VEditorKit/Classes/VEditorTextCellNode.swift
  VEditorKit/Classes/VEditorTextNode.swift
  VEditorKit/Classes/VEditorTextStorage.swift
  VEditorKit/Classes/VEditorTypingControlNode.swift
  VEditorKit/Classes/VEditorVideoNode.swift
Labels: enhancement

#5 VEditorKit: Bind Typing Attribute Event Handling
  Example/VEditorKit/EditorControlAreaNode.swift
  Example/VEditorKit/EditorNodeController.swift
  VEditorKit/Classes/Platform.swift
  VEditorKit/Classes/VEditorNode.swift
  VEditorKit/Classes/VEditorTextCellNode.swift
  VEditorKit/Classes/VEditorTextNode.swift
  VEditorKit/Classes/VEditorTextStorage.swift
Labels: enhancement

#7 Development: Synchronize contents fetching logic
  Example/VEditorKit/EditorNodeController.swift
  VEditorKit/Classes/VEditorNode.swift
Labels: enhancement

#10 media is able to delete and merge text
  Example/VEditorKit/EditorNodeController.swift
  Example/VEditorKit/EditorRule.swift
  Example/VEditorKit/content.xml
  VEditorKit/Classes/VEditorDeleteMediaNode.swift
  VEditorKit/Classes/VEditorImageNode.swift
  VEditorKit/Classes/VEditorNode.swift
  VEditorKit/Classes/VEditorOpenGraphNode.swift
  VEditorKit/Classes/VEditorTextNode.swift
  VEditorKit/Classes/VEditorVideoNode.swift
Labels: enhancement

#11 Video management test
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  Example/VEditorKit.xcodeproj/xcshareddata/xcschemes/VEditorKit-Example.xcscheme
  Example/VEditorKit/EditorControlAreaNode.swift
  Example/VEditorKit/EditorNodeController.swift
  Example/VEditorKit/EditorRule.swift
  Example/VEditorKit/content.xml
  VEditorKit/Classes/VEditorDeleteMediaNode.swift
  VEditorKit/Classes/VEditorVideoNode.swift
Labels: enhancement

#12 Support Open Graph Preview (og-object preview) with example
  Example/VEditorKit/EditorNodeController.swift
  Example/VEditorKit/EditorRule.swift
  Example/VEditorKit/content.xml
  VEditorKit/Classes/VEditorOpenGraphNode.swift
Labels: enhancement

#14 Editor follow caret offset on scroll area
  VEditorKit/Classes/VEditorNode.swift
  VEditorKit/Classes/VEditorTextNode.swift
Labels: enhancement

#15 Fix keyboard height bug: replace keyboardFrame begin to end userInfoKey
  Example/VEditorKit/EditorRule.swift
  VEditorKit/Classes/VEditorNode.swift
Labels: bug

#20 Refactoring VEditorKit
  Example/VEditorKit/EditorNodeController.swift
  Example/VEditorKit/EditorRule.swift
  VEditorKit/Classes/Platform.swift
  VEditorKit/Classes/VEditorDeleteMediaNode.swift
  VEditorKit/Classes/VEditorImageNode.swift
  VEditorKit/Classes/VEditorMediaPlaceholderNode.swift
  VEditorKit/Classes/VEditorNode.swift
  VEditorKit/Classes/VEditorOpenGraphNode.swift
  VEditorKit/Classes/VEditorParser.swift
  VEditorKit/Classes/VEditorTextCellNode.swift
  VEditorKit/Classes/VEditorTextNode.swift
  VEditorKit/Classes/VEditorTypingControlNode.swift
  VEditorKit/Classes/VEditorVideoNode.swift
  VEditorKit/Classes/VEditorXMLBuilder.swift
Labels: enhancement

#22 Fix un-sync between textStorage size with editableNode viewFrame
  VEditorKit/Classes/VEditorTextNode.swift
  VEditorKit/Classes/VEditorTextStorage.swift
Labels: enhancement

#24 image & video insert test able
  Example/VEditorKit/EditorNodeController.swift
  VEditorKit/Classes/VEditorImageNode.swift
  VEditorKit/Classes/VEditorNode.swift
  VEditorKit/Classes/VEditorVideoNode.swift
Labels: enhancement

#25 VEditorKit: Fetch new content safty
  Example/VEditorKit/EditorNodeController.swift
  VEditorKit/Classes/VEditorNode.swift
  VEditorKit/Classes/VEditorTextCellNode.swift
  VEditorKit/Classes/VEditorTextNode.swift
Labels: bug

#26 refactoring VEditorMediaContents
  Example/VEditorKit/EditorNodeController.swift
  VEditorKit/Classes/VEditorDeleteMediaNode.swift
  VEditorKit/Classes/VEditorImageNode.swift
  VEditorKit/Classes/VEditorMediaNode.swift
  VEditorKit/Classes/VEditorNode.swift
  VEditorKit/Classes/VEditorOpenGraphNode.swift
  VEditorKit/Classes/VEditorTextCellNode.swift
  VEditorKit/Classes/VEditorTextNode.swift
  VEditorKit/Classes/VEditorTextStorage.swift
  VEditorKit/Classes/VEditorVideoNode.swift
Labels: enhancement

#28 VEditorKit TextStorage Unit Test
  Example/Tests/VEditorImageNodeSpec.swift
  Example/Tests/VEditorMediaNodeSpec.swift
  Example/Tests/VEditorMediaPlaceholderNodeSpec.swift
  Example/Tests/VEditorParserSpec.swift
  Example/Tests/VEditorTextCellNodeSpec.swift
  Example/Tests/VEditorTextNodeSpec.swift
  Example/Tests/VEditorTextStorageSpec.swift
  Example/Tests/VEditorTypingControlNodeSpec.swift
  Example/Tests/VEditorVideoNodeSpec.swift
  Example/Tests/VEditorXMLBuilderSpec.swift
  Example/VEditorKit.xcodeproj/project.pbxproj
  Example/VEditorKit/XMLViewController.swift
  VEditorKit/Classes/VEditorDeleteMediaNode.swift
  VEditorKit/Classes/VEditorParser.swift
  VEditorKit/Classes/VEditorTextNode.swift
  VEditorKit/Classes/VEditorTextStorage.swift
Labels: enhancement

#29 VEditorNode Unit Test
  Example/Tests/VEditorNodeSpec.swift
  Example/VEditorKit.xcodeproj/project.pbxproj
  VEditorKit/Classes/VEditorNode.swift
Labels: enhancement

#31 Fix huge text paste out of memory issue
  VEditorKit/Classes/VEditorTextStorage.swift
  screenshots/typingControl.gif
Labels: bug

#36 [Feature] flexible media content node
  VEditorKit/Classes/VEditorDeleteMediaNode.swift
  VEditorKit/Classes/VEditorImageNode.swift
  VEditorKit/Classes/VEditorMediaNode.swift
  VEditorKit/Classes/VEditorOpenGraphNode.swift
  VEditorKit/Classes/VEditorVideoNode.swift
Labels: bug, enhancement

#38 Support convenience xml to NSAttributedString parser with editor rule
  Example/Tests/VEditorParserSpec.swift
  VEditorKit/Classes/VEditorParser.swift
Labels: enhancement

#39 fix safe area insets on typing control area layoutSpec & ready for release hot fix v1.2.1
  VEditorKit.podspec
  VEditorKit/Classes/VEditorNode.swift
Labels: bug

#41 use NSDataDetector with NSTextCheckingResult.CheckingType.link
  Example/Tests/VEditorTextNodeSpec.swift
  VEditorKit/Classes/VEditorTextNode.swift
  VEditorKit/Classes/VEditorTextStorage.swift
Labels: enhancement

#43 Ready for Release v1.3.0
  Example/VEditorKit.xcodeproj/project.pbxproj
  Example/VEditorKit/AppDelegate.swift
  Example/VEditorKit/Controllers/EditorNodeController.swift
  Example/VEditorKit/Controllers/XMLViewController.swift
  Example/VEditorKit/EditorServices/EditorRule.swift
  Example/VEditorKit/EditorServices/VImageContent.swift
  Example/VEditorKit/EditorServices/VOpenGraphContent.swift
  Example/VEditorKit/EditorServices/VVideoContent.swift
  Example/VEditorKit/Extensions/UIImage+Extension.swift
  Example/VEditorKit/Services/MockService.swift
  Example/VEditorKit/Views/EditorControlAreaNode.swift
  Example/VEditorKit/Views/EditorOpenGraphPlaceholder.swift
  VEditorKit.podspec
  VEditorKit/Classes/Platform.swift
Labels: enhancement

#45 VEditorKit: If user insert media at last then automatically make empt…
  Example/Tests/VEditorNodeSpec.swift
  VEditorKit/Classes/VEditorNode.swift
Labels: enhancement

#47 Fix Invalid Merge Issue
  Example/VEditorKit.xcodeproj/project.pbxproj
  VEditorKit/Classes/VEditorNode.swift
  VEditorKit/Classes/VEditorParser.swift
Labels: bug
